fix TypeError
this fixes
TypeError: Argument 1 does not allow None as a value
which is thrown on archlinux, see
https://aur.archlinux.org/packages/solaar/